#!/usr/bin/env bash
################################################################
# This script gets a coder's data from its handle
# Example: 
# tc-data-from-handle Steven
# 
################################################################
if [ -z "$1" ]; then
  echo -e "\033[0;31mError: handle is missing!\033[0m"
  exit 1
fi
curl -s "api.topcoder.com/v2/users/$1"
##################### END ###################################

