#!/usr/bin/env bash
################################################################
# This script gets a coder's handle from its identification number
# Example:
# > tc-handle-from-id 101459
# > Steven
################################################################
if ! [[ $1 =~ ^[0-9]+$ ]]; then
  echo -e "\033[0;31mError: invalid coder identification number!\033[0m"
  exit 1
fi
curl -s -L --max-redirs 1 -i "community.topcoder.com/tc?module=MemberProfile&cr=$1" | grep -E 'members/' | sed -E "s/.*\/members\///"
##################### END ###################################
