#!/usr/bin/env bash

# Sanity checks
if [ -z $1 ]; then
  echo -e "\033[0;31mError: xml file is missing!\033[0m"
  exit 1
fi
if [ -z $2 ]; then
  echo -e "\033[0;31mError: xml field is missing!\033[0m"
  echo -e "\033[0;31mTry with one of these:\033[0m"
  xml el -u "$1"
  exit 2
fi

# Parser
# Example xml_to_csv <name file> <id field>
xml sel -t -m "$2" -m "*" -o '"' -v "." -o '"' -i 'not(position()=last())' -o "," --else -n "$1"

exit 0