#!/bin/bash
now=`date +%b%d`
main_file=patents.Rmd

# Directories
paper_dir=Paper
paper_html_dir=Paper_html
paper_docx_dir=Paper_docx
paper_appendix=Appendix
config_dir=Config
share_dir=.share

# Utility funciton
function compile {
  output_dir="$1"
  cp Templates/* $output_dir/Templates
  cp .RData *.Rmd $output_dir
  cd $output_dir && crmd $main_file && mv *.Rmd Code/
  cd ..
}


if [ "$1" == "--docx" ]; then
  echo "Compiling docx..."
  cp $config_dir/_output_docx.yml $paper_docx_dir/_output.yml
  compile $paper_docx_dir
  
elif [ "$1" == "--pdf" ]; then
  echo "Compiling pdf..."
  cp $config_dir/_output.yml $paper_dir
  cp $config_dir/*.py $paper_dir
  compile $paper_dir

elif [ "$1" == "--all" ]; then
  echo "Compiling all formats..."
  cp $config_dir/_output.yml $paper_dir
  cp $config_dir/*.py $paper_dir
  cp $config_dir/_output_docx.yml $paper_docx_dir/_output.yml
  cp $config_dir/_output_html.yml $paper_html_dir/_output.yml
  compile $paper_dir && pwd && compile $paper_docx_dir && compile $paper_html_dir
  
else 
  echo "Compiling html..."
  cp $config_dir/_output_html.yml $paper_html_dir/_output.yml
  cp $config_dir/*.py $paper_html_dir
  compile $paper_html_dir
fi

## Sharable folder
# mkdir -p $share_dir
# cp $paper_dir/report.pdf $share_dir/mgh_report_$now.pdf
# cp $paper_docx_dir/report.docx $share_dir/mgh_report_$now.docx
# cp $paper_appendix/report_appendix.pdf $share_dir/mgh_appendix_$now.pdf

